---
- name: apt-get
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ raspberry_pi_install_target }}"

- name: services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - slurmd
